version: "3.7"

services: 
    database_exchange:
        image: postgres
        container_name: database_exchange
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=exchange
            - POSTGRES_DB=exchange
        volumes: 
            - pgdata:/data/postgres
    app:
        build: .
        container_name: exchange
        ports: 
            - 3333:3333
        volumes:
            - .:/usr/app
        links: 
            - database_exchange
        depends_on: 
            - database_exchange

volumes: 
    pgdata:
        driver: local